version: "3"

services:
  glue.local:
    build:
      context: ./
    container_name: gluelocal
    volumes:
      - ./src:/opt/src/src
      - ./tests:/opt/src/tests
      - aws-glue-lib_bin:/aws-glue-libs/bin
      - aws-glue-libs_conf:/aws-glue-libs/conf
      - aws-cli-conf:/root/.aws
    environment:
      # dummy configure
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_DEFAULT_OUTPUT=json
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # localstack公式テンプレ
  # localstack:
  #   container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
  #   image: localstack/localstack
  #   network_mode: bridge
  #   ports:
  #     - "4566:4566"
  #     - "4571:4571"
  #     - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
  #   environment:
  #     - SERVICES=${SERVICES- }
  #     - DEBUG=${DEBUG- }
  #     - DATA_DIR=${DATA_DIR- }
  #     - PORT_WEB_UI=${PORT_WEB_UI- }
  #     - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
  #     - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #     - HOST_TMP_FOLDER=${TMPDIR}
  #     - DEFAULT_REGION=ap-northeast-1
  #   volumes:
  #     - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"

volumes: 
  aws-glue-lib_bin:
  aws-glue-libs_conf:
  aws-cli-conf:
    

